version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    # ignore:
    #   # Ignore updates to packages that start 'aws'
    #   # Wildcards match zero or more arbitrary characters
    #   - dependency-name: "aiohttp*"
    #   #      - dependency-name: "urllib3*"
    #   - dependency-name: "matplotlib"
